### ISSUE TITLE
Fix Automation for 0.50.x releases

### ISSUE THREAD

**Issue by brianjking** [brianjking/homeassistant-config#113]
* Re: https://github.com/home-assistant/home-assistant/pull/8510
* https://home-assistant.io/docs/automation/trigger/#time-trigger
* https://home-assistant.io/docs/automation/trigger/#state-trigger

**Comment by brianjking** [comment]
@amelchio -- Can you possibly take a look at my automations and see why I'm still not complying with the changes in `0.50.x`? I feel like I'm going crazy but can't pinpoint what issue/file is causing the problem.

https://github.com/brianjking/homeassistant-config/tree/master/automation

Thanks....

**Comment by arsaboo** [comment]
I quickly checked couple of your automations and you have them wrong. `from` `to` are only required in `trigger`. You need to use `state` in `condition`.

**Comment by brianjking** [comment]
@arsaboo I think I got it fixed, thanks! 

Think it's fixed in bf5f9a43c7f772f64f326003b559feeedc0785d8

* No errors reported in HASS UI
* No errors reported in Travis-CI build 300 https://travis-ci.org/brianjking/homeassistant-config/builds/262755816
