### ISSUE TITLE
USPS -- Attempt to setup using kylefrost today-mail setup using Selenium

### ISSUE THREAD

**Issue by brianjking** [brianjking/homeassistant-config#125]
* https://github.com/happyleavesaoc/python-myusps/issues/9
* https://github.com/kylefrost/todays-mail

**Comment by brianjking** [comment]
https://home-assistant.io/developers/component_loading/

**Comment by J-CMartin** [comment]
So I got it working for mail count sensor using Kyle's code inside myusps running with the latest homeassistant version. The code is very simple, but as mentioned before, it requires Chrome and other libraries to be installed along with homeassistant. I've tested it in a Docker environment and it wasn't easy to install Chrome. had to manually install dependencies and then download and install latest chrome. Other requirements were installed using pip and can be automated likely.

**Comment by brianjking** [comment]
@J-CMartin -- Nice! I'm on Hassbian, can you please advise as to how I can go about getting this setup?

Are you going to submit a PR here for @happyleaves to merge?

Thanks!

**Comment by brianjking** [comment]
Fixed in `myusps==1.3.2` using `PhantomJS` method. https://github.com/happyleavesaoc/python-myusps/issues/9

**Comment by brianjking** [comment]
`pip3 install --upgrade --force-reinstall myusps==1.3.2`
