### ISSUE TITLE
New screenshots for readme

### ISSUE THREAD

**Issue by brianjking** [brianjking/homeassistant-config#65]

**Comment by CCOSTAN** [comment]
How do you make your animated Gifs?

**Comment by KinnaT** [comment]
[ScreenToGif](http://www.screentogif.com/) is my personal favorite.

**Comment by brianjking** [comment]
@CCOSTAN As @KinnaT mentioned [ScreenToGif](http://www.screentogif.com/) is a great open source Windows app which is what I used for the update I posted today.

If I'm using my Mac I use Screenflow, which is generally for more in-depth recordings (generally video with voiceovers, callouts, etc.), however, it can also do simple exports as animated Gifs.
